init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

branches:
  only:
    - master

install:
  - ps: Bootstrap
  - cmd: git submodule update --init --recursive
  - cmd: git clone https://github.com/CxxTest/cxxtest
  - cmd: cd c:\tools\vcpkg
  - cmd: vcpkg integrate install
  - cmd: vcpkg install gsl:x64-windows
  - cmd: cd "%APPVEYOR_BUILD_FOLDER%"

cache:
  - C:\RLibrary
    
environment:
  global:
    R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    _R_CHECK_FORCE_SUGGESTS_: false
    USE_RTOOLS: true
    WARNINGS_ARE_ERRORS:
    R_VERSION: release
    R_ARCH: x64
    R_CHECK_ARGS: --as-cran

# This is the minimal set of R packages needed to run "R CMD check" on
# the package.
build_script:
  - R -e install.packages(c('devtools','testthat','R6','RcppGSL','ggplot2','abind','mvtnorm','matrixStats','progress'),head(.libPaths(),1),'http://cran.wustl.edu')
  - R -e devtools::install_github('stephens999/ashr',upgrade='never',force=TRUE)
  - R -e devtools::install_github('stephenslab/mashr',upgrade='never',force=TRUE)
  - R -e devtools::install_github('stephenslab/susieR',upgrade='never',force=TRUE)  

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
